ER図作成
shootaa/quelcode-db pull request #1
Opened 2020-06-29 14:42 UTC by shootaa

やったこと
ER図の作成

2020-06-30 03:10 UTC, Yuzunoha commented
- [ ] テーブルのタイトルのところに主キー書いちゃってますね。vscodeのer図を書く画面の左にある検索バーで `er` と検索すると `ER Table 1` や `ER Table 2` が出てくるので使ってください
- [ ] 書き中

2020-06-30 07:54 UTC, shootaa commented
・vscodeのERtableを使用しました。
・リレーションを見直し修正しました。

2020-07-01 04:25 UTC, yusaku-inamura requested changes
みましたー 🙆‍♂️ 

下記確認して修正お願いします。

- ユーザーテーブルに電話番号1、電話番号2という論理名がついていますが、今回の場合要件から勤務先用の電話番号登録用のカラムと携帯電話用のカラムというように用途がはっきりしていますので、具体的な名前をつけた方が良さそうです。
- タスクテーブルが構造上実質的に中間テーブルとなっていますが、本当に正しいでしょうか?
例えば実際にシステムを構築する際に特定のタスクを完了させたい場合、対象のタスクを一意に絞り込むことができる必要がありますが、今の構造でできるでしょうか?
- 表記の問題ではありますが、タスクは必ず提出をもって完了とする訳ではないので、 `提出済み` ではなく単純に `完了フラグ` などとしてあげるのが良いでしょう。
- リレーションの表記が片方しかされていません。例として、チャットルームから見た時にチャットが0または多なのはわかりますが、チャットルームはチャットから見た時にどのような関係となるでしょうか?

2020-07-01 04:57 UTC, shootaa commented
014de35e9529491bcc0b88f1bc68016a5ab03ac9
上記のコミットで対応しました！
・ユーザーテーブルの電話番号1、電話番号2を携帯電話番号、勤務先電話番号に変更しました
・主キーをタスクIDとしました。
・提出済を完了フラグとしました。
・リレーションを見直しました。

以上よろしくお願いします！！

2020-07-02 07:15 UTC, piasoratech requested changes
細かい部分もありますが、以下指摘事項です
- ユーザーテーブルとタスクテーブルの間にあるつながっていないリレーションについて不要であれば削除、必要であれば繋げてください。
- 作成日や更新日というカラムがありますが、今回の要件では時間も保持してもらうので適切な名前に修正して下さい。
- テーブル内のカラムは日時系や作成者・更新者の情報が一番後ろに来ることが多いので順番を入れ替えておきましょう

2020-07-02 07:34 UTC, shootaa commented
bb9daaf81e63726d95a2714c901df322bc75376c
このコミットで対応しました！
・リレーションをきちんとつなげました。
・全て日時としました。
・作成日時、更新日時、作成者、更新者がカラムの最後になるようにしました。

以上よろしくお願いします！

2020-07-02 09:57 UTC, piasoratech requested changes
以下の内容の確認をお願いします
- タスクテーブルにタスクの担当者情報を保持するカラムがないです。
- タスクテーブルとユーザーテーブルのリレーションはどのカラムを外部キーとする想定でしょうか？それによって指摘内容が変わるので回答をお願いします。

2020-07-02 10:07 UTC, shootaa commented
1161aa7908484a36d728660a9a9ff74618168f67
このコミットで対応しました。
・タスクテーブルにユーザーIDカラムを追加しました。
・追加したユーザーIDカラムを外部キーとします。

以上よろしくお願いします！

2020-07-02 10:55 UTC, himaru-jp commented
「タスクテーブル」の「ユーザID」では、どのようなユーザなのか分かりません。
もう少し具体的な名称にしましょう！

2020-07-02 11:05 UTC, shootaa commented
7879e279d2b87fc066b383cfb95124c6743a7017
このコミットで対応しました！
・名称を担当者IDとしました。

以上よろしくお願いします！

2020-07-03 02:17 UTC, piasoratech requested changes
項目についてはOKですが、体裁を整えましょう。
ドキュメント類は常に他人が見ることを意識して作成してください。
![image](https://user-images.githubusercontent.com/57445698/86424913-c6c9bd80-bd1e-11ea-8c83-bb05ba39a97c.png)

2020-07-03 02:22 UTC, shootaa commented
988dd1b2d17d935cf9d384cdb783eb9355ecdd1c
このコミットで対応しました。
・カラムを整えました。

以上よろしくお願いします！

2020-07-03 04:05 UTC, Yuzunoha commented
- [ ] ユーザーとタスクテーブル間の線は消してよいです。ユーザーとチャット間には線が無いので。今回は自明なFKは線を省略することで統一しましょう。
- [ ] チャットルーム参加者はチャットルームに対して0以上ではなく1以上ではないでしょうか！

- [ ] aaa(書き中)
- [ ] aaa

2020-07-03 06:16 UTC, shootaa commented
ecd39e884bc829d60cf07722f9d0f7e303a919ba
このコミットで対応しました。
・チャットルーム参加者はチャットルームに対して1以上としました。
・チャットルームはチャットに対して1としました。
・FKマークもカラム名の左側に記載しました。
・チャットルーム参加者テーブルは ER Table 2 を使いました。

以上よろしくお願いします！

2020-07-03 06:51 UTC, Yuzunoha commented
OKです！！承認しました！！！

>FKマークもカラム名の左側に記載しました。

こちらは
チャットルームID（FK）
チャットルームID(FK)
等が未対応ですね。

とはいえ見栄えの問題なので修正不要です！！次に進んでください！！！

2020-07-03 06:52 UTC, Yuzunoha approved these changes
OKです！！承認しました！！！

>FKマークもカラム名の左側に記載しました。

こちらは
チャットルームID（FK）
チャットルームID(FK)
等が未対応ですね。

とはいえ見栄えの問題なので修正不要です！！次に進んでください！！！

2020-07-04 13:10 UTC, merged