やったこと
shootaa/quelcode-db pull request #2
Opened 2020-07-04 13:24 UTC by shootaa

・データベース定義書の作成
・DDL文の作成

2020-07-06 04:52 UTC, piasoratech reviewed
- テーブル名は複数形にしましょう
- int型の場合も長さは指定してください
- フラグ系のカラムの型はMySQLにおいてint型を使用するのは一般的ではないです。調べて変更しましょう
- TipsにあるQiitaの記事を確認して、修正すべき部分は修正をお願いします。

2020-07-06 06:19 UTC, shootaa commented
435bd21f6aab84e2e30f7427231144ab12ed41d2
このコミットで対応しました。
・テーブル名を複数形にしました。
・int型の長さも記載しました。
・boolean型にしました。
・tipsを見てtable名を直しました。

2020-07-06 07:04 UTC, piasoratech requested changes
- フラグ系のカラムはMySQLだと内部的にtinyintで管理するので定義するときもtinyintを使いましょう。
- 外部キーの設定の仕方が間違っているので確認してください。
- 要件を満たせていない部分があるので確認して修正してください。
- 作成者IDや更新者IDにも外部キーを設定して下さい。

2020-07-06 07:04 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +      `is_submitted` boolean DEFAULT 0 NOT NULL,
submitの意味にファイル送信を許可するといった意味は含まれていないと思いますので、適切な名前を付けましょう。

2020-07-06 08:07 UTC, shootaa commented
9465f42841e0150939f8a7365b31156f59018e0b
・tinyintにしました。
・外部キーのテーブル名を変更しました。
・外部キーの設定を見直しました。

2020-07-06 08:53 UTC, piasoratech requested changes
コメントしたので確認をお願いします！
提出する前にチェックをよくしてください。

2020-07-06 08:53 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +      `chatroom_id` int(11) NOT NULL REFERENCES chatrooms(ID),
まだ外部キーの書き方が正しくないので、修正して下さい。

2020-07-06 08:53 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +      `is_deleted` tinyint DEFAULT 0 NOT NULL,
tinyintを使う場合も長さは指定します。

2020-07-06 08:53 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +      `file_permission` tinyint DEFAULT 0 NOT NULL,
できる限りカラム名を見ただけでtrueの場合どういった状態でfalseの場合どういった状態になるかが分かるほうが良いです。

2020-07-06 08:53 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +      `is_directed` tinyint DEFAULT 0 NOT NULL,
今回の場合は「directだった」状態を示したいわけではないので過去形にしなくて大丈夫です

2020-07-06 08:53 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +      `office_telephonenumber` int(13),
int型の場合-が入れられません

2020-07-06 08:53 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +      `updated_at` tinyint NOT NULL,
ここは日時が入るので、型が違います

2020-07-06 08:53 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +      `owner_id` int(11)  NOT NULL REFERENCES users(ID),
このカラム名の場合タスクを作成した人なのか、タスクの担当者なのかは判別がつかないので名前を修正してください

2020-07-06 09:32 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +      `office_telephonenumber` int(13),
varchar型に変更しました

2020-07-06 09:32 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +      `updated_at` tinyint NOT NULL,
datetimeにしました！

2020-07-06 09:33 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +      `is_deleted` tinyint DEFAULT 0 NOT NULL,
長さ指定しました！

2020-07-06 09:36 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +      `is_directed` tinyint DEFAULT 0 NOT NULL,
is_direct_chatに変更しました

2020-07-06 09:38 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +      `owner_id` int(11)  NOT NULL REFERENCES users(ID),
task_manager_idに変更しました。

2020-07-06 09:41 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +      `file_permission` tinyint DEFAULT 0 NOT NULL,
is_file_sendableに変更しました！

2020-07-06 09:48 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +      `chatroom_id` int(11) NOT NULL REFERENCES chatrooms(ID),
書き方を修正しました！

2020-07-06 10:12 UTC, piasoratech requested changes
DB定義書に関する指摘です。
- DDLと定義書に記載されている内容で異なる部分があるので修正をしましょう。
- 体裁が整っていない部分があるので、体裁を整えてください。
- 通し番号が通しになっていない部分があります。

2020-07-06 10:12 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +      `is_file_sendable` tinyint(1) DEFAULT 0 NOT NULL,
ここのデフォルト値が要件と合っていないです

2020-07-06 10:12 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +      `office_telephonenumber` varchar(13),
telephoneとnumberの間に_を入れましょう
スネークケースは単語ごとに_を入れます。

2020-07-06 13:25 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +      `is_file_sendable` tinyint(1) DEFAULT 0 NOT NULL,
d68757c858b80f6354f80f91f30bd1dfdab05c53
このコミットで対応しました。

2020-07-06 13:25 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +      `office_telephonenumber` varchar(13),
d68757c858b80f6354f80f91f30bd1dfdab05c53
このコミットで対応しました。

2020-07-06 13:26 UTC, shootaa commented
ec27cf7abc454ef5a8fb7899c8a471e4ef8b12ed
その他、定義書とDDLのずれについてはこのコミットで修正しました！

2020-07-07 02:58 UTC, himaru-jp requested changes

2020-07-07 02:58 UTC, himaru-jp commented on db/db-challenge2/chatwork.sql
> +CREATE TABLE `users-chatrooms` (
物理名にハイフンを使用するとライブラリで誤動作を起こしたり、常にバッククウォートで囲わないといけないため、使用しないようにしてください。

2020-07-07 02:58 UTC, himaru-jp commented on db/db-challenge2/chatwork.sql
> +      `chatroom_id` int(11) NOT NULL REFERENCES chatrooms(id),
外部キー制約をつけるため、依存関係を考慮してCREATE TABLE文の順番を考えましょう！

2020-07-07 02:58 UTC, himaru-jp commented on db/db-challenge2/chatwork.sql
> +      `join_at` datetime NOT NULL,
「参加した日」なので、ここは過去・過去分詞が適切です。

2020-07-07 05:58 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +CREATE TABLE `users-chatrooms` (
01690b4856e7a1594a545e16cbb3ee39d84ad539
スネークケースに修正しました。

2020-07-07 05:59 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +      `chatroom_id` int(11) NOT NULL REFERENCES chatrooms(id),
01690b4856e7a1594a545e16cbb3ee39d84ad539
順番変更しました。

2020-07-07 05:59 UTC, shootaa commented on db/db-challenge2/chatwork.sql
> +      `join_at` datetime NOT NULL,
01690b4856e7a1594a545e16cbb3ee39d84ad539
過去形に修正しました！

2020-07-07 06:53 UTC, fjtawork commented
確認しました。OKです

2020-07-07 07:41 UTC, merged